# Generated by Django 6.0.8 on 2026-08-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="course",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
