# Generated by Django 6.0.8 on 2026-08-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_resourceanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="studyresource",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="past_papers/"),
        ),
    ]
