# Generated by Django 6.0.8 on 2026-08-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_studyresource_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="studyresource",
            name="exam_board",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
