# Generated by Django 6.0.8 on 2026-08-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0007_studyresource_exam_board"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="source_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="note",
            name="title",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="note",
            name="transcription_source",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
